env: dev4
#eureka:
 # client:
  #  service-url:
   #   defaultZone: http://localhost:8762/eureka/
server:
  port: 8082
  tomcat:
    max-http-form-post-size: 3145728
spring:
  application:
    name: order
  datasource:
    username: root
    password: 123456
    url:   jdbc:mysql://localhost:3308/pm10?useUnicode=true&serverTimezone=CTT
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.1.15
    username: guest
    password: guest
    port: 5672
PRODUCT:
  ribbon:
#    NIWSServerListClassName: com.netflix.loadbalancer.RandomRule
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#PRODUCT:
#  ribbon:
#   NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  client:
    default:
      #这里时间一定要调长，否则feign客户端会报ReadTimeOut  服务端报Error parsing HTTP request header
      connectTimeout: 60000
      readTimeout: 60000
      loggerLevel: basic
